# Generated by Django 5.1.2 on 2024-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patriotpath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('career_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
